---
- name: "Install app"
  hosts: all
  become: true
  vars:
    SECRET_KEY_BASE : any
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: 1
    DB_HOST: 127.0.0.1
    DB_PORT: 5432
    DB_NAME: test_base
    DB_USER: user
    DB_PASSWORD: password
    ruby_version: 2.6.9
    app_name: xpaste_practicum-master
    app_user: app
  
  roles: 
    - postgres
    - app
    #- geerlingguy.nginx
  tasks:
    - name: install nginx
      vars:
        nginx_conf_template: template/nginx.conf.j2
        nginx_user: app
      ansible.builtin.include_role:
        name: geerlingguy.nginx
        tasks_from: main

  


